# Random seed for reproducibility
random_seed: 12345

# Where is prepared data
prepared_data_path: ./data/raw_data.parquet

preparation_params:
  start_date: "2023-01-01"
  end_date: "2024-12-31"

dataset_params:
  sequence_length: 256
  morpher_spec:
    description: [categorical, {}]
    pitch_name: [categorical, {}]
    release_speed: [numeric, {n_quantiles: 64}]
    plate_x: [numeric, {n_quantiles: 64}]
    plate_z: [numeric, {n_quantiles: 64}]
    pfx_x: [numeric, {n_quantiles: 64}]
    pfx_z: [numeric, {n_quantiles: 64}]

dataloader_params:
  # Generic examples.
  batch_size: 512
  num_workers: 0

trainer_params:
  # Examples
  precision: bf16-mixed
  max_epochs: 16
  accumulate_grad_batches: 1
  log_every_n_steps: 20

model_params:
  d_model: 256
  n_transformer_layers: 4
  n_kv: 4
  n_q: 8
  positional_encoding: "nope"

optimizer_params:
  # These are just the Adam defaults.
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0