# Random seed for reproducibility
random_seed: 12345

# Where is prepared data
prepared_data_path: ./data/raw_data.parquet

preparation_params:
  start_date: "2023-01-01"
  end_date: "2024-12-31"

dataset_params:
  note: For dataset configuration

dataloader_params:
  # Generic examples.
  batch_size: 512
  num_workers: 0

trainer_params:
  # Examples
  precision: bf16-mixed
  max_epochs: 16
  accumulate_grad_batches: 1
  log_every_n_steps: 20

model_params:
  note: For model

optimizer_params:
  # These are just the Adam defaults.
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0